import type { Metadata } from "next";
import { Header } from "@/components/header/Header";
import "@/styles/globals.css";
import { ProductsProvider } from "@/context/ProductsProvider";
import { CartProvider } from "@/context/CartProvider";

export const metadata: Metadata = {
  title: "Project Games",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body >
        <CartProvider>
          <Header />
          <ProductsProvider>
            {children}
          </ProductsProvider>
        </CartProvider>
      </body>
    </html>
  );
}
